server:
  port : 8081
spring:
  servlet:
    multipart:
      enabled: true
  datasource:
    url: jdbc:mysql://localhost:3306/cloudstorage
    username: root
    password: mysqlAlOch
  jpa:
    hibernate:
      ddl-auto: create-drop
    generate-ddl: true
    show-sql: true
  security:
    jwt:
      token:
        secret-key: secret-key
        expire-length: 300000 # 5 minutes duration by default: 5 minutes * 60 seconds * 1000 milliseconds