server:
  port : 8081

spring:
  servlet:
    multipart:
      enabled: true

  datasource:
    url: jdbc:mysql://localhost:3306/cloudstorage
    username: root
    password: mysqlAlOch

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true