server:
  port : 8081

spring:
  servlet:
    multipart:
      enabled: true

  datasource:
    url: jdbc:mysql://localhost:3306/cloudstorage
    username: root
    password: mysqlAlOch

#  datasource:
#    url: jdbc:mysql://localhost:3366/cloudstorage
#    username: root
#    password: mysql

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true