### Test data
### user1 / pass1
### auth-token: Bearer eyJhbGciOiJIUzUxMiJ9.eyJqdGkiOiJzb2Z0dGVrSldUIiwic3ViIjoidXNlcjEiLCJhdXRob3JpdGllcyI6WyJST0xFX1VTRVIiXSwiaWF0IjoxNjM5NDE3MDc1LCJleHAiOjE2Mzk0MTc2NzV9.RiTNcwcqh-d4LQ3MkNlfFTn68nUy5aLhLOkqEl743ssgk23HC0keL8ZAIDDas1oqHOpwYn5Yi7TyphRVZ6Z5XQ

###login user
POST http://localhost:8081/login
Content-Type: application/json

{
  "login": "user1",
  "password": "pass1"
}
### list of files
GET http://localhost:8081/list?limit=3
auth-token: Bearer uyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJ1c2VyMSIsImV4cCI6MTYzOTUxMjc4MywiaWF0IjoxNjM5NDk0NzgzfQ.sqDYwUIgzqbxfuWhLxOIInssNDhfJ5hT1MGHjfFWT_rjb7SwWLBRA4804IZ_qKAT8xT-dV_a18ULZBFmRTOuCQ

### upload file
POST http://localhost:8081/file?filename=557.txt
auth-token: Bearer uyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJ1c2VyMSIsImV4cCI6MTYzOTUxMjc4MywiaWF0IjoxNjM5NDk0NzgzfQ.sqDYwUIgzqbxfuWhLxOIInssNDhfJ5hT1MGHjfFWT_rjb7SwWLBRA4804IZ_qKAT8xT-dV_a18ULZBFmRTOuCQ
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="file"; filename="557.txt"

test
--WebAppBoundary

### edit file name

PUT http://localhost:8081/file?filename=601.txt
auth-token: Bearer yJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJ1c2VyMSIsImV4cCI6MTY0MjE5OTUxMiwiaWF0IjoxNjQyMDE5NTEyfQ.CZXOp55hv2k1M8EtHhzF6QjZffOzTYYKFWQR8E-Ag45EFCHNkyQ0ALAzpcVHLlmOBXIvSOmxg3inuFX22Yk1yA
Content-Type: application/json

{
  "filename": "444.txt"
}

###

DELETE http://localhost:8081/file?filename=948.txt
auth-token: Bearer pyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJ1c2VyMyIsImV4cCI6MTYzOTY4MTczNSwiaWF0IjoxNjM5NTAxNzM1fQ.PRfJaKu2esDx3Uh6QLJbdyGrqMzloRF64FOhaqPC4k6uoDk5kNPKcZMGVZ_zVTQSIfAuoaJO7WGHoOnvmCr1kw
